name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build containers
        run: docker compose -f docker-compose.yml build
      
      - name: Start only the database (Postgres) in background
        run: docker compose -f docker-compose.yml up -d postgres

      - name: Wait for Postgres to be ready
        run: |
          echo "Esperando a que Postgres inicie..."
          until nc -z localhost 5432; do
            echo "Postgres no está listo aún..."
            sleep 1
          done
          echo "¡Postgres está listo!"

      - name: Run NestJS tests
        run: docker compose -f docker-compose.yml run --rm nestjs yarn test

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.yml down -v
